import type { Metadata } from "next";
import { Zen_Kaku_Gothic_New } from "next/font/google";
import "@/styles/globals.css";
import Link from "next/link";

import { cn } from "@/lib/utils";

const zenkakuGN = Zen_Kaku_Gothic_New({
	weight: ["400", "700"],
	preload: false,
	display: "swap",
});

import { ThemeProvider } from "@/components/theme-provider";
import Sidebar from "./ui/sidebar";
import Header from "./ui/header";
import Footer from "./ui/footer";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ja">
			<body
				className={cn(
					"min-h-screen h-svh bg-background font-initial tracking-wide antialiased ",
					zenkakuGN.className
				)}
			>
				<ThemeProvider
					attribute="class"
					defaultTheme="dark"
					enableSystem
					// disableTransitionOnChange
				>
					<div className="grid w-full h-full grid-cols-1 grid-rows-[80px_1fr_320px] relative justify-center justify-items-center content-between gap-4">
						<Header />
						<div className="max-w-[1440px] w-full h-full grid lg:grid-cols-[1fr_320px] md:grid-cols-[1fr_300px] sm:grid-cols-1 gap-2 px-2">
							{children}
							<Sidebar />
						</div>
						<Footer />
					</div>
				</ThemeProvider>
			</body>
		</html>
	);
}
